name: Deploy to S3

on:
  push:
    branches: [main]
    paths:
      - 'index.html'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: |
          aws s3 cp index.html s3://inventory-app-finalproject/index.html
      - name: Configure Static Website Hosting
        run: |
          aws s3 website s3://inventory-app-finalproject/ --index-document index.html
