name: Super-Linter

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON: true
          VALIDATE_HTML: true
          VALIDATE_HTML_PRETTIER: true
          VALIDATE_PYTHON_BLACK: true
          FIX_PYTHON_BLACK: true
          FIX_HTML_PRETTIER: true
